import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = (path: string): string =>
  readFileSync(new URL(`./src/${path}`, import.meta.url), 'utf8').replace(/\r\n?/g, '\n')

describe('observation chamber markup contracts', () => {
  const monitor = source('views/MonitorView.vue')
  const card = source('components/ui/Card.vue')
  const modal = source('components/ui/Modal.vue')
  const chamber = source('components/monitor/ObservationChamber.vue')
  const chart = source('components/monitor/ObservationTrendChart.vue')
  const i18n = source('composables/useI18n.ts')

  it('opens every monitor group from its whole interactive card surface', () => {
    expect(monitor.match(/<Card :title=/g) ?? []).toHaveLength(7)
    expect(monitor.match(/interactive/g) ?? []).toHaveLength(7)
    expect(monitor.match(/:expanded=/g) ?? []).toHaveLength(7)
    expect(monitor.match(/controls="observation-chamber"/g) ?? []).toHaveLength(7)
    expect(monitor.match(/@activate="openObservation\('/g) ?? []).toHaveLength(7)
    expect(monitor).not.toContain('observation-open')
    expect(card).toContain(":role=\"interactive ? 'button' : undefined\"")
    expect(card).toContain("if (event.key === 'Enter' || event.key === ' ')")
    expect(card).toContain("closest('a, button, input, select, textarea, [contenteditable=\"true\"]')")
    expect(card).toContain('window.getSelection()?.toString()')
  })

  it('mounts one observation dialog and derives geometry from the owning card', () => {
    expect(monitor.match(/<ObservationChamber/g) ?? []).toHaveLength(1)
    expect(monitor).toContain('card.getBoundingClientRect()')
    expect(monitor).toContain('getBoundingClientRect()')
    expect(monitor).toContain('originRect.value =')
    expect(monitor).toContain(':origin-rect="originRect"')
    expect(monitor).toContain('onBeforeRouteLeave')
    expect(monitor).toContain('watch(() => session.current')
    expect(chamber.match(/<Modal/g) ?? []).toHaveLength(1)
    expect(chamber).toContain('variant="observation"')
    expect(chamber).toContain(':origin-rect="originRect"')
    expect(chamber).toContain('id="observation-chamber"')
  })

  it('loads real history with a retryable generation guard', () => {
    expect(chamber).toContain('fetchObservationHistory')
    expect(chamber).toContain('createObservationRequestGuard')
    expect(chamber).toContain('new AbortController()')
    expect(chamber).toContain('guard.isCurrent')
    expect(chamber).toContain("t('common.retry')")
    expect(chamber).toContain("t('observation.empty')")
    expect(chamber).toContain("t('observation.partial_warning')")
    expect(chamber).toContain('primary-grid')
    expect(chamber).toContain('detail-grid')
    expect(chamber).toContain('latestValues')
    expect(chamber).toContain('storageLimit')
    expect(chamber).toContain('oldestLabel')
    expect(chamber).toContain("trendState === 'loading'")
    expect(chamber).toContain("trendState === 'error'")
    expect(chamber).toContain("trendState === 'empty' && loading")
    expect(chamber).toContain("trendState === 'empty' && error")
    expect(chamber).toContain("t('observation.related')")
    expect(chamber).toContain('readingLabel')
    expect(chamber).toContain('chamber-header')
    expect(chamber).toContain('reading-row')
    expect(chamber).toContain('lower-panel')
    expect(chamber).toContain('metadata-list')
    expect(chamber).toContain("t('observation.explanation')")
    expect(chamber).toContain('v-if="meterPercent(reading) !== undefined"')
    expect(chamber).not.toContain("'28%'")
    expect(i18n.match(/'observation\.explanation'/g) ?? []).toHaveLength(2)
  })

  it('renders only real normalized history on an accessible canvas', () => {
    expect(chart).toContain('<canvas')
    expect(chart).toContain('role="img"')
    expect(chart).toContain(':aria-label=')
    expect(chart).toContain('buildTrendSeries')
    expect(chart).toContain('point.first')
    expect(chart).toContain('fromTimestamp')
    expect(chart).toContain('plot')
    expect(chart).toContain('drawWhiskers')
    expect(chart).toContain('point.min')
    expect(chart).toContain('legend')
    expect(chart).not.toContain('Math.random')
    expect(chart).not.toContain('synthetic')
  })

  it('keeps the generic modal focus and dismissal contracts backward compatible', () => {
    expect(modal).toContain("export type ModalSize = 'sm' | 'md' | 'lg'")
    expect(modal).toContain("variant?: 'standard' | 'observation'")
    expect(modal).toContain("<Teleport to=\"body\">")
    expect(modal).toContain("if (e.key === 'Escape')")
    expect(modal).toContain("if (e.key === 'Tab') trapFocus(e)")
    expect(modal).toContain('@mousedown.self="onBackdropClick"')
    expect(modal).toContain('lastFocused.value?.focus()')
    expect(modal).toContain('aria-modal="true"')
    expect(modal).toContain('backdrop-observation')
    expect(modal).toContain('blur(2px)')
    expect(modal).toContain('morphFromRect')
    expect(modal).toContain('prefersReducedObservationMotion')
    expect(modal).toContain('.animate(')
    expect(modal).toContain('visibility = \'hidden\'')
    expect(modal).toContain('.catch(() => {})')
    expect(modal).toContain('1100px')
    expect(modal).toContain('76dvh')
    expect(modal).toContain('var(--bg) 96%')
    expect(modal).toContain('var(--bg) 28%')
  })
})
